services:
  wordlist-front:
    image: nataliasemka17/wordlist:1.0.0
    container_name: wordlist-front
    ports:
      - "81:80"

  dictionary-server:
    image: k9nz00/dictionary:1.0.0
    restart: always
    ports:
      - "8080:8080"
      - "38005:38005"
    environment:
      DB_JDBC_URL: jdbc:postgresql://postgres:5432/dictionary
      DB_USER: dictionary
      DB_PWD: dictionary
      DB_POOL_SIZE: 20
      FORMAT_DATE: yyyy-MM-dd
      FORMAT_TIME: HH:mm:ss
      FORMAT_DATE_TIME: yyyy-MM-dd HH:mm:ss
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dictionary
      POSTGRES_PASSWORD: dictionary
      POSTGRES_DB: dictionary
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8090:8080
    environment:
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      - DOZZLE_ENABLE_ACTIONS=true

      # Uncomment to allow access to container shells. See https://dozzle.dev/guide/shell
      - DOZZLE_ENABLE_SHELL=true

volumes:
  postgres_data:
